import SwiftUI

/// Loads the bundled strokes.json (generated by Tools/build_strokes.py from KanjiVG).
@Observable
final class StrokeLibrary {
    enum LoadState {
        case loading
        case ready
        case failed(String)
    }

    private(set) var loadState: LoadState = .loading
    private var characters: [String: CharacterStrokes] = [:]

    func load() async {
        guard characters.isEmpty else { return }
        guard let url = Bundle.main.url(forResource: "strokes", withExtension: "json")
            ?? Bundle.main.url(forResource: "strokes", withExtension: "json", subdirectory: "Resources")
        else {
            loadState = .failed("strokes.json is missing from the app bundle.")
            return
        }
        do {
            characters = try await Task.detached(priority: .userInitiated) {
                let data = try Data(contentsOf: url)
                return try JSONDecoder().decode([String: CharacterStrokes].self, from: data)
            }.value
            loadState = .ready
        } catch {
            loadState = .failed(error.localizedDescription)
        }
    }

    func strokes(for character: Character) -> CharacterStrokes? {
        characters[String(character)]
    }
}
