import SwiftUI

/// Stroke-order data for one character, in KanjiVG's 109×109 coordinate space.
nonisolated struct CharacterStrokes: Decodable, Sendable {
    /// SVG path data for each stroke, in writing order.
    let strokes: [String]
    /// Where KanjiVG places each stroke's number label (text baseline, left edge).
    let numberPositions: [CGPoint]

    static let canvasSize: CGFloat = 109

    private enum CodingKeys: String, CodingKey {
        case strokes = "s"
        case numberPositions = "n"
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        strokes = try container.decode([String].self, forKey: .strokes)
        let raw = try container.decodeIfPresent([[Double]].self, forKey: .numberPositions) ?? []
        numberPositions = raw.compactMap { $0.count == 2 ? CGPoint(x: $0[0], y: $0[1]) : nil }
    }
}

/// Loads the bundled strokes.json (generated by Tools/build_strokes.py from KanjiVG).
@Observable
final class StrokeLibrary {
    enum LoadState {
        case loading
        case ready
        case failed(String)
    }

    private(set) var loadState: LoadState = .loading
    private var characters: [String: CharacterStrokes] = [:]

    func load() async {
        guard characters.isEmpty else { return }
        guard let url = Bundle.main.url(forResource: "strokes", withExtension: "json")
            ?? Bundle.main.url(forResource: "strokes", withExtension: "json", subdirectory: "Resources")
        else {
            loadState = .failed("strokes.json is missing from the app bundle.")
            return
        }
        do {
            characters = try await Task.detached(priority: .userInitiated) {
                let data = try Data(contentsOf: url)
                return try JSONDecoder().decode([String: CharacterStrokes].self, from: data)
            }.value
            loadState = .ready
        } catch {
            loadState = .failed(error.localizedDescription)
        }
    }

    func strokes(for character: Character) -> CharacterStrokes? {
        characters[String(character)]
    }
}
